### ISSUE TITLE
Finishing Out Trends Page

### ISSUE THREAD

**Issue by jennxu23** [CS342/2023-Utah#103]
### Use Case

The user will use the trends page to look at their survey scores and passive data.

### Problem

The Trends Page needs to be finished.

### Solution

N/A

### Alternatives considered

To finish the trends page for the final presentation:
1) Create a datacard for each survey that the user has taken, populated with their most recent scores.
2) Move the charts into a sheet that is triggered each time the user taps on a data card.
3) Small UI changes 
4) Possibly populate charts with actual data. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by jenlmoore** [comment]
Done!
