### ISSUE TITLE
Get Authentication working with Firebase

### ISSUE THREAD

**Issue by jenlmoore** [CS342/2023-Utah#22]
### Problem

Our backend is not connected to our app yet.

### Solution

Connect the firebase acct/console with the app.
Start with user authentication here, will go to storing the user info next.

### Additional context

Please make sure **all** test cases pass AND upload screenshots of your changes!

If you can, please make a branch off of this issue and split it up into as many PRs as possible.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
The auth portion of the backend is set up now, all you need to do is remove the emulator settings on line 31 of `UtahAppDelegate.swift` (highlighted below) to have the app log in via the Firebase backend instead!

![Screenshot 2023-02-23 at 7 50 24 PM](https://user-images.githubusercontent.com/1212163/221064918-4b55c87f-1347-44c6-929a-8d3fe392e0c7.png)
