### ISSUE TITLE
Survey Question #11: Get Up and Go test backend

### ISSUE THREAD

**Issue by jenlmoore** [CS342/2023-Utah#28]
### Problem

We need our backend to start a timer and track the time it takes the user to walk. We need to track how far they walk too, in order to give them the vibration to turn around.

### Solution

- Create a 'stopwatch' in the backend that starts the time as soon as the 'start' button is clicked.
- Let the user know when they hit 3meters (vibration and ding)

### Additional context

Please make sure all test cases pass AND upload screenshots of your changes!

If you can, please make a branch off of this issue and split it up into as many PRs as possible.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by BKrajancich** [comment]
Closing, since we'll now use the Walk Test. New issue #43
