### ISSUE TITLE
Implement VEINES-QOL/Sym questionnaire frontend

### ISSUE THREAD

**Issue by BKrajancich** [CS342/2023-Utah#35]
### Use Case

Used to assess the veinous disease

### Problem

More specificity for the researchers:
https://www.sciencedirect.com/science/article/pii/S0895435606000515#aep-figure-id9

### Solution

Implement using ResearchKit

### Alternatives considered

CardinalKit, but rest of the surveys use ResearchKit

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by jenlmoore** [comment]
Finished.
