### ISSUE TITLE
Create Figma Workflow/UI

### ISSUE THREAD

**Issue by jenlmoore** [CS342/2023-Utah#4]
### Problem

Everything is currently a template

### Solution

Create a cohesive design for all necessary pages. Only UI changes should be here.
* enough customization for the presentation
* keep the skeleton of template, just add customizations like color, fonts, etc

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ivyalin2015** [comment]
https://www.figma.com/file/El092r7tlcKGxFQG9JZJUp/CS-342-Utah-Project---User-Flow-UI?node-id=0%3A1&t=4IZBZ8Z5CG9twkuE-1
