### ISSUE TITLE
Get ResearchKit questionaires exporting in FHIR format

### ISSUE THREAD

**Issue by BKrajancich** [CS342/2023-Utah#41]
### Use Case

To upload data to Firebase in FHIR format

### Problem

Want FHIR

### Solution

ResearchKitOnFHIR?

### Alternatives considered

Custom

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
This is a tricky one @BKrajancich, happy to help you with it.

**Comment by BKrajancich** [comment]
I'd appreciate that @vishnuravi!

It seems like I need something like [this](https://github.com/StanfordBDHG/ResearchKitOnFHIR/blob/main/Example/ExampleApp/Responses/ORKTaskFHIRDelegate.swift) from the ResearchKitOnFHIR Example App, I'm just trying to figure out how to put the result in the MockDataStorageProvider. Slowly making progress!

**Comment by BKrajancich** [comment]
Scope covered by #42
