### ISSUE TITLE
Add date of birth collection to onboarding

### ISSUE THREAD

**Issue by BKrajancich** [CS342/2023-Utah#49]
### Use Case

Mentors want the user's DOB to be able to more easily look them up in their records

### Problem

We don't currently collect DOB

### Solution

- Add a date selector step to the onboarding (just before what Condition? screen)
- Push to firebase (under user)

### Alternatives considered

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by jenlmoore** [comment]
will do! J wondering, where/when did they say to add that? I want to make sure Im not missing anything else

**Comment by BKrajancich** [comment]
@jenlmoore Teryn included it on the "copy" doc I sent them yesterday. There may be more incoming...

**Comment by jenlmoore** [comment]
They decided to not include this :(
