### ISSUE TITLE
Onboarding View UI updates

### ISSUE THREAD

**Issue by jenlmoore** [CS342/2023-Utah#5]
### Problem

Current Onboarding view is the template, we want it to be our app designs/ wording.

### Solution

Update the current UI view to display our designs
* only UI for right now
* take out any unnecessary information
* add the wording that our PI's gave us in the google doc if possible

@emmyxth + @BKrajancich

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by BKrajancich** [comment]
@jenlmoore is this supposed to be Onboarding Flow* updates? The Form/Questionnaire is in a decent state for this Thursday's deliverables (I think)

**Comment by jenlmoore** [comment]
@BKrajancich Sorry! You're completely right, thanks for catching!
