### ISSUE TITLE
Change name field labels in onboarding

### ISSUE THREAD

**Issue by vishnuravi** [CS342/2023-Utah#60]
### Problem

Mentors have asked for name field labels in onboarding to be changed from *Given Name* and *Family Name* to *First Name* and *Last Name*. This is currently not configurable in CardinalKit.

### Solution

The following open PR on CardinalKit will make these fields configurable and sets the default to the labels needed: https://github.com/StanfordBDHG/CardinalKit/pull/54. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by jenlmoore** [comment]
Completed, marking as done.
