### ISSUE TITLE
Font size updates

### ISSUE THREAD

**Issue by BKrajancich** [CS342/2023-Utah#71]
### Problem

The default font size is too small for our user base

### Solution

Let's make it bigger! Also consistent across all pages in:
- Onboarding
- Surveys

Here's a helpful overview of the pages: https://www.figma.com/file/szFlVU5e8nV7iRHKK9U93F/Untitled?node-id=0%3A1&t=WYnt2IT3xCxmbWbZ-1

Please use your best judgement and send screenshots to the mentors for feedback. Need by EOD Wednesday, top priority!!

### Additional context

I think you saw Paul's post about how to do this already but just in case: https://github.com/orgs/CS342/discussions/35

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by jenlmoore** [comment]
Decided to just keep it the way it is and direct the patients to increase overall font size on their phone.
