### ISSUE TITLE
Clock test images aren't getting to Firebase

### ISSUE THREAD

**Issue by BKrajancich** [CS342/2023-Utah#72]
### Description

I've tried building the app (in debug) mode on my phone and I can't find the photograph on Firebase. The rest of the surveys are uploading great though.

### Reproduction

Try doing the Edmonton survey on device (the camera capture is not available on the Desktop emulator), the photo does not appear in Firebase

### Expected behavior

Photograph should appear in firebase, and linked to the original survey submission object

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by jenlmoore** [comment]
I can look into this
