### ISSUE TITLE
Create Survey Questions

### ISSUE THREAD

**Issue by jenlmoore** [CS342/2023-Utah#8]
### Problem

We don't have the survey questions in the app that we should ask the patients.

### Solution

Create and upload the correct survey questions (Edmonton Frail Scale) into the app
* for questions 1 and 10, provide the wording with a numerical answer, we will update them later

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by BKrajancich** [comment]
@jenlmoore I accidentally did this while working on the question UI issue. You okay if I just push it on your behalf? Sorry, didn't mean to step on your toes!!

**Comment by jenlmoore** [comment]
@BKrajancich No problem at all 🫡 I was going to get to it tonight so you did me a favor. Push away!
