### ISSUE TITLE
Create Questionnaire linking based on diagnosis

### ISSUE THREAD

**Issue by BKrajancich** [CS342/2023-Utah#92]
### Use Case

Want secondary questionnaire triggered based on diagnosis

### Problem

Above

### Solution

Should be triggered after Edmonton

### Alternatives considered

Clicking on a separate questionnaire

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by jenlmoore** [comment]
Done in PR #104 and PR #102
