### ISSUE TITLE
Get questionnaire score displaying after completion

### ISSUE THREAD

**Issue by BKrajancich** [CS342/2023-Utah#93]
### Use Case

When a user completes a questionnaire, wants to see their outcome without having to go to the Trends tab

### Problem

Not easy to do this via ResearchKit pre-designed pages

### Solution

Create a custom page?

### Alternatives considered

Not sure

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by jenlmoore** [comment]
Done using custom view at end! PR #109
